language: python
python:
  - '3.5'
install:
  - 'pip3 install homeassistant'
  - 'mv hass/settings/secrets.yaml.sample hass/settings/secrets.yaml'
script:
  - 'cd hass/settings/ && hass -c . --script check_config | tee check.output'
  - '! less check.output | grep -q ERROR'

