esphome:
  name: bath_light
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_24_name
  password: !secret wifi_24_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "BathLight Fallback Hotspot"
    password: !secret esphome_captive_pass

logger:

api:
  password: !secret esphome_pass

ota:
  password: !secret esphome_pass

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    id: button_1
    on_press:
      then:
        - light.toggle: light_1

  - platform: status
    name: "Bath status"

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

light:
  - platform: binary
    name: "bath"
    id: light_1
    output: relay_1

status_led:
  pin:
    number: GPIO13
    inverted: yes