- platform: mqtt
  name: bath
  state_topic: "stat/bathlight/POWER"
  command_topic: "cmnd/bathlight/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: xiaomi_miio
  name: bath_led
  host: !secret philips_downlight_ip
  token: !secret philips_downlight_token