- platform: mqtt
  state_topic: 'home/kitchen-led/$uptime'
  name: 'uptime_kitchen-led'
- platform: mqtt
  state_topic: 'home/nest/$uptime'
  name: 'uptime_nest'
- platform: mqtt
  state_topic: 'tele/bathlight/UPTIME'
  name: 'uptime_bathlight'
- platform: mqtt
  state_topic: 'tele/kitchen/UPTIME'
  name: 'uptime_kitchen'
- platform: mqtt
  state_topic: 'home/noolite/$stats/uptime'
  name: 'uptime_salt_lamp'