#################################################
#            CAR TRAVEL TIME                    #
#################################################
- platform: yandex_maps
  start: !secret home_coords
  destination: !secret work_coords
  name: monster_travel_time_home_to_work
- platform: yandex_maps
  start: !secret work_coords
  destination: !secret home_coords
  name: monster_travel_time_work_to_home