- platform: template
  sensors:
    counter_hot_money_monthly:
      friendly_name: "Горячая в мес"
      unit_of_measurement: 'Р'
      value_template: "{{ (states('sensor.counter_hot_monthly') | float * 188.53) | round(2) }}"    
    counter_cold_money_monthly:
      friendly_name: "Холодная в мес"
      unit_of_measurement: 'Р'
      value_template: "{{ (states('sensor.counter_cold_monthly') | float * 38.06) | round(2) }}"    
    power_money_monthly:
      friendly_name: "Электричество в мес"
      unit_of_measurement: 'Р'
      value_template: "{{ (states('sensor.power_monthly') | float * 4.37) | round(2) }}"    
    dishwasher_money_monthly:
      friendly_name: "Посудомойка в мес"
      unit_of_measurement: 'Р'
      value_template: "{{ (states('sensor.dishwasher_monthly') | float * 4.37) | round(2) }}"    
    washer_money_monthly:
      friendly_name: "Стиралка в мес"
      unit_of_measurement: 'Р'
      value_template: "{{ (states('sensor.washer_monthly') | float * 4.37) | round(2) }}"    
    tv_money_monthly:
      friendly_name: "ТВ в мес"
      unit_of_measurement: 'Р'
      value_template: "{{ (states('sensor.tv_monthly') | float * 4.37) | round(2) }}"    
    thermopot_money_monthly:
      friendly_name: "Термопот в мес"
      unit_of_measurement: 'Р'
      value_template: "{{ (states('sensor.thermopot_monthly') | float * 4.37) | round(2) }}"    
    conditioner_money_monthly:
      friendly_name: "Кондиционер в мес"
      unit_of_measurement: 'Р'
      value_template: "{{ (states('sensor.conditioner_monthly') | float * 4.37) | round(2) }}"    
