ARG BASE_IMAGE
#FROM acockburn/appdaemon:${BASE_IMAGE}
FROM ${BASE_IMAGE}

RUN pip3 install \
      attrs==19.1.0 \
      emp_mos_api==0.10 \
      packaging==16.8 \
      python-Levenshtein==0.12.0 \
      voluptuous==0.11.5
