- platform: mqtt
  name: "kitchen_mini_light"
  state_topic: "home/plug/kitchen-mini-light/status"
  command_topic: "home/plug/kitchen-mini-light/status/set"
  payload_on: "on"
  payload_off: "off"
  retain: false
